//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelManagamenStudio
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class hotel5Entities : DbContext
    {
        public hotel5Entities()
            : base("name=hotel5Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<bookings> bookings { get; set; }
        public virtual DbSet<employees> employees { get; set; }
        public virtual DbSet<guests> guests { get; set; }
        public virtual DbSet<payments> payments { get; set; }
        public virtual DbSet<rooms> rooms { get; set; }
    }
}
