//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelManagamenStudio
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class payments
    {
        public int payment_id { get; set; }
        public Nullable<int> booking_id { get; set; }
        public Nullable<int> amount { get; set; }
        public Nullable<int> additional_payement { get; set; }
    
        public virtual bookings bookings { get; set; }
    }
}
